* Introduction
  There are 2 (currently) projects in [[https://github.com/winfred-lu/stm32f4-bluenrg][stm32f4-bluenrg]] that can be run on [[http://www.st.com/web/catalog/tools/FM116/SC959/SS1532/LN1199/PF259098icmp%3Dstm32f401discovery_pron_footer_jan2014&sc%3Dstm32f401discovery][32F401CDiscovery]] boards.

** Sensor project
   A sensor demo project for STM32F401 Discovery board in conjunction with a BlueNRG module.

   The BlueNRG app allows you to access the sensor data directly from the mobile device over Bluetooth Low Energy.

   The STM32F401 Discovery creates a GATT (Generic Attribute Profile) vendor characteristic, and several services including the one reporting Accelerometer data. The mobile phone (BlueNRG app) connecting the board, aquires Accelerometer data, and visualizes it with a 3D cube.

** Audio playback and record
   This projects shows the usages of the Audio DAC [[http://www.cirrus.com/en/products/cs43l22.html][CS43L22]] and ST MEMS microphone [[http://www.st.com/web/catalog/sense_power/FM125/SC1564/PF251680sc%3Dinternet/analog/product/251680.jsp][MP45DT02]]. User can switch between to play or record an audio by pressing USER button.

   1. Play an audio. Device CS43L22
      By default, it plays "audio.wav" that is on the USB Mass Storage (LED6 toggle). A click on the board pauses the audio playing(LED6 on ).

   2. Record and play an audio. Device MP45DT02
      After the USER button is pressed, it starts recording in the USB Mass Storage (LED3 toggle). When the recorded wave length is around 30 seconds or interrupted by pressing the USER button.

* Requirements
** Hardware
   Two devices are needed:
   - [[http://www.st.com/web/catalog/tools/FM116/SC959/SS1532/LN1199/PF259098icmp%3Dstm32f401discovery_pron_footer_jan2014&sc%3Dstm32f401discovery][32F401CDiscovery]]
   - The BlueNRG module (daughter board of [[http://www.st.com/web/en/catalog/tools/PF259562][STEVAL-IDB002V1]])

   The connection between F401CDiscovery and BlueNRG board is 5-wire SPI, which is a standard 4-wire SPI with an additional IRQ pin. The IRQ pin is for BlueNRG module to notify F401CDiscovery to receive packets.

** Software
   - GNU toolchain
     The latest release ([[https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q2-update][4.8 currently]]) of [[https://launchpad.net/gcc-arm-embedded/%2Bdownload][GNU Tools for ARM Embedded Processor]] is known to work.
   - Flash tool
     Either [[http://openocd.sourceforge.net/][openocd]] or [[https://github.com/texane/stlink][stlink]] works.
   - BlueNRG app (see below)
   - (optional) [[https://itunes.apple.com/us/app/lightblue-bluetooth-low-energy/id557428110mt%3D8][LightBlue]], [[https://itunes.apple.com/us/app/ble-utility/id606210918mt%3D8][BLE Utility]]
     Great BLE utilities for BLE developers.

   BlueNRG app is available for both Android and iPhone:
   - [[https://play.google.com/store/apps/detailsid%3Dcom.st.bluenrg][Google play BlueNRG]]
   - [[https://itunes.apple.com/us/app/bluenrg/id705873549mt%3D8][iTunes BlueNRG]]

* Download, Build and Run
  Clone the project:
  #+BEGIN_EXAMPLE
    git clone https://github.com/winfred-lu/stm32f4-bluenrg.git
  #+END_EXAMPLE

  Build the project:
  #+BEGIN_EXAMPLE
    make clean
    make
    make flash
  #+END_EXAMPLE

  Start the BlueNRG app and connect.

** Demo video
   - [[http://youtu.be/snkItabFmWU][Sensor project demo]]
   - [[http://youtu.be/cFi-fe3H9fs][Audio project demo]]
